version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - cache
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    volumes:
      - pgdata:/var/lib/postgresql/data

  cache:
    image: redis:latest
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
